import type { QrConfig } from "./qr";

export interface Preset {
  id: string;
  name: string;
  swatch: string;
  config: Partial<QrConfig>;
}

export const PRESETS: Preset[] = [
  {
    id: "classic",
    name: "Classic",
    swatch: "linear-gradient(135deg,#111827,#374151)",
    config: {
      dotType: "square",
      fgMode: "solid",
      fgColor: "#111827",
      cornerSquareType: "square",
      cornerDotType: "square",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#ffffff",
      shape: "square",
    },
  },
  {
    id: "rounded",
    name: "Soft",
    swatch: "linear-gradient(135deg,#0f172a,#475569)",
    config: {
      dotType: "extra-rounded",
      fgMode: "solid",
      fgColor: "#0f172a",
      cornerSquareType: "extra-rounded",
      cornerDotType: "dot",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#f8fafc",
      shape: "square",
    },
  },
  {
    id: "dots",
    name: "Bubbles",
    swatch: "radial-gradient(circle,#22d3ee,#6366f1)",
    config: {
      dotType: "dots",
      fgMode: "gradient",
      fgGradientType: "radial",
      fgGradientFrom: "#22d3ee",
      fgGradientTo: "#6366f1",
      cornerSquareType: "dot",
      cornerDotType: "dot",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#ffffff",
      shape: "square",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    swatch: "linear-gradient(135deg,#2563eb,#06b6d4)",
    config: {
      dotType: "rounded",
      fgMode: "gradient",
      fgGradientType: "linear",
      fgGradientFrom: "#2563eb",
      fgGradientTo: "#06b6d4",
      fgGradientRotation: 45,
      cornerSquareType: "extra-rounded",
      cornerDotType: "dot",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#ffffff",
      shape: "square",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    swatch: "linear-gradient(135deg,#f97316,#ec4899)",
    config: {
      dotType: "classy-rounded",
      fgMode: "gradient",
      fgGradientType: "linear",
      fgGradientFrom: "#f97316",
      fgGradientTo: "#ec4899",
      fgGradientRotation: 60,
      cornerSquareType: "extra-rounded",
      cornerDotType: "dot",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#fff7ed",
      shape: "square",
    },
  },
  {
    id: "forest",
    name: "Forest",
    swatch: "linear-gradient(135deg,#059669,#84cc16)",
    config: {
      dotType: "rounded",
      fgMode: "gradient",
      fgGradientType: "linear",
      fgGradientFrom: "#059669",
      fgGradientTo: "#65a30d",
      fgGradientRotation: 30,
      cornerSquareType: "extra-rounded",
      cornerDotType: "dot",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#f7fee7",
      shape: "square",
    },
  },
  {
    id: "mono-circle",
    name: "Coin",
    swatch: "radial-gradient(circle,#111827,#4b5563)",
    config: {
      dotType: "dots",
      fgMode: "solid",
      fgColor: "#111827",
      cornerSquareType: "dot",
      cornerDotType: "dot",
      cornerMode: "custom",
      cornerColor: "#111827",
      cornerDotColor: "#111827",
      bgMode: "solid",
      bgColor: "#ffffff",
      shape: "circle",
    },
  },
  {
    id: "night",
    name: "Night",
    swatch: "linear-gradient(135deg,#e879f9,#38bdf8)",
    config: {
      dotType: "classy",
      fgMode: "gradient",
      fgGradientType: "linear",
      fgGradientFrom: "#e879f9",
      fgGradientTo: "#38bdf8",
      fgGradientRotation: 120,
      cornerSquareType: "extra-rounded",
      cornerDotType: "dot",
      cornerMode: "match",
      bgMode: "solid",
      bgColor: "#0b1120",
      shape: "square",
    },
  },
];
